name: Cargar Historial (Manual)

on:
  workflow_dispatch: # Esto crea el botón para ejecutarlo manualmente

jobs:
  extraccion-pasada:
    runs-on: ubuntu-latest
    steps:
      - name: Traer el código
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar herramientas (En la nube)
        run: pip install requests beautifulsoup4 supabase

      - name: Ejecutar el Robot Explorador 🚀
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python cargar_historial.py
