name: Robot del Boletin Oficial

on:
  schedule:
    # Se ejecuta de lunes a viernes a las 11:00 UTC (que son las 08:00 AM en Argentina)
    - cron: '0 11 * * 1-5'
  workflow_dispatch: # Esto nos agrega un botón para correrlo a mano cuando queramos probarlo

jobs:
  ejecutar-scrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Traer el código
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar herramientas
        run: pip install requests supabase

      - name: Despertar al Robot 🤖
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python robot.py
